# Generated by Django 5.0.6 on 2024-06-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football.tournament'),
        ),
    ]
