# Generated by Django 5.0.6 on 2024-06-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_team_code_alter_group_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='away_goals',
            new_name='away_bet',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='home_goals',
            new_name='home_bet',
        ),
    ]
