# Generated by Django 5.0.6 on 2024-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_rename_away_goals_bet_away_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
